import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/navBar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(" bg-black text-white", inter.className)}>
        <NavBar />
        {/* <Toaster /> */}
        <div className="flex justify-center items-center pt-32">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
