import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/navBar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themeProvider";
import { MainNav } from "@/components/dashboard/mainNav";
import { Search } from "lucide-react";
import { UserNav } from "@/components/dashboard/userNav";
import TeamSwitcher from "@/components/dashboard/teamSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(" bg-black text-white", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" z-50 fixed w-screen">
            <NavBar />
          </div>

          {/* <Toaster /> */}
          <div className="flex justify-center items-center  pt-24">
            {children}
          </div>
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
